### PR TITLE
Use flake8-print to catch leftover debug/print statements.

### PR DESCRIPTION
**Pull request by jessemyers**
This library just adds a rule that tells the linter to flag all prints.

In most cases, print statements are an error; production code ought to
use log statements. If there are exceptions (e.g. CLI output), developers
just need to add the usual #noqa exception.

### CODE REVIEW

**Comment by jessemyers** [comment]
I'm assuming `cookiecutter` doesn't magically fix existing projects and I'll have to edit the configuration separately for each of the following:
 - diego
 - escolastica (is this valid? builds are failing currently)
 - florentino
 - juvenal
 - leona 
 - lorenze
 - marquez-api-python
 - marquez-integration-tests (doesn't seem to be running linting at all)
 - oscar
 - remedios
 - transito

**Comment by adamhadani** [comment]
LGTM! 
1. Yep those services will need to be updated I think u listed them all. Escolastica is out of commission but will be brought back to life soon very likely so useful to keep it maintained with these things if possible
2. Installing it automatically makes running flake8 use it? No need for further configuration / CLI flags?

**Comment by jessemyers** [comment]
1. I'll need to figure out Jira-ing next to keep track of that list. I don't want my todo list to be this PR.
2. Yes, installing `flake8-print` is all that it needs. There's a [setuptools entrypoint](https://github.com/JBKahn/flake8-print/blob/master/setup.py#L37) for extending flake8.

Who is responsible for merging?

**Comment by cdm-ium** [comment]
Just `git flow feature finish` and push. We try to get a thumbs up before
merging but we do our own merges.

**Pull request merged**
