### PR TITLE
Update app config to use _SETTINGS for config from file

### PR DESCRIPTION
**Pull request by srt32**
Updates `configure_app` to read config `from_envvar` using an
environment variables as we're already doing in [other
apps](https://github.com/globality-corp/transito/blob/develop/transito/app.py#L55-L63).

### CODE REVIEW

**Comment by adamhadani** [comment]
@srt32  hmm I already applies this on develop (and other stuff I backported) - weird that u see this diff still in PR..it's identical to your version in develop right now I believe

**Comment by srt32** [comment]
Whatttt...

**Comment by adamhadani** [comment]
@srt32 let's verify state of this weird non-existing diff today and see if any reason to merge ths after all or can safely close

**Comment by srt32** [comment]
Perhaps my branch needs a rebase and the diff will go away?

**Comment by adamhadani** [comment]
@srt32 could be, try it out and let's see

**Comment by srt32** [comment]
Yup, after a rebase this PR had no diff and the PR auto closed.

**Pull request closed without merging**
